"""" File for customizing Vim

"""" Basic Behavior
set number                  " show line numbers
set wrap                    " wrap lines
set encoding=utf-8          " set encoding to UTF-8
set mouse=a                 " enable mouse support (might not work well on Mac OS X)
set wildmenu                " visual autocomplete for command menu
set wildchar=<TAB>          " show possible completions.
set showmatch               " highlight matching parentheses / brackets [{()}]
set spelllang=en_us         " spell checking
set autoread                " reload files if changed externally
set pastetoggle=p           " paste mode: avoid auto indent


"""" Vim Appearance
colorscheme rupza           " color settings --> ~/.vim/colors/
filetype plugin indent on   " use filetype-based ftplugins and indentation
syntax on                   " use filetype-based syntax highlighting


"""" Vim Aliases 
command W wq                " Fast save and quit
command Q q!                " Fast force quit

" Sudo Save
cmap w!! w !sudo tee % > /dev/null 